"""added breed

Revision ID: 901dc0764e6e
Revises: 
Create Date: 2021-01-14 13:27:12.401916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '901dc0764e6e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('breed')
    # ### end Alembic commands ###
