"""Adding like

Revision ID: a8167e0c3150
Revises: 3a8999a1eee8
Create Date: 2021-01-15 09:38:04.273139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8167e0c3150'
down_revision = '3a8999a1eee8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dog_id_give', sa.Integer(), nullable=False),
    sa.Column('dog_id_receive', sa.Integer(), nullable=False),
    sa.Column('dislike', sa.Boolean(), nullable=False),
    sa.Column('match', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('like')
    # ### end Alembic commands ###
